title: Nadia Ainiah Rahma Ghozali # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a third year Economics student at Universitas Airlangga. I have actively participated in various campus organizations and committees for the last 3 years and still ensure that my academics run in a balanced condition. I have great interest in Planning and Development, Social Media Management, and Data Analytics. I have a desire to explore new things, can work under pressure, adaptable, and reliable to work in a team. I currently being the Head of Research and Development Bureau in BEM FEB UNAIR 2022.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/nadiaainiah/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
