title: Nadia Ainiah Rahma Ghozali # your name (or website title) here
logo: "images/foto profil github nadia.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a third year Economics student at Universitas Airlangga. I have great interest in Planning and Development, Social Media Management, and Data Analytics.
   <br><br>
  This is my online portfolio. Enjoy!
  <br><br>
  <a href="https://www.linkedin.com/in/nadiaainiah/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
